#!/usr/bin/env bash
# Sentinel Agent Installer
#
# Designed to be piped through curl:
#   curl -fsSL https://raw.githubusercontent.com/cocacolasante/Sentinel/main/sentinel-agent/install.sh \
#     | AGENT_ID="..." AGENT_TOKEN="..." BRAIN_URL="wss://..." bash
#
# Can also be run directly from a local clone:
#   AGENT_ID="..." ... bash /path/to/install.sh
#
# Required env vars: AGENT_ID, AGENT_TOKEN
# Optional env vars: BRAIN_URL, APP_NAME, APP_DIR, APP_PROCESS_NAME,
#                    APP_HEALTH_URL, APP_LOG_PATH, APP_RESTART_CMD,
#                    SENTINEL_ENV, HEARTBEAT_INTERVAL

set -euo pipefail

INSTALL_DIR="/opt/sentinel-agent"
ENV_DIR="/etc/sentinel-agent"
SERVICE_USER="sentinel-agent"
REPO_URL="${SENTINEL_AGENT_REPO:-https://github.com/cocacolasante/Sentinel.git}"
AGENT_SUBDIR="sentinel-agent"

echo "==> Installing Sentinel Agent"

# ── Validate required vars ────────────────────────────────────────────────────
if [ -z "${AGENT_ID:-}" ] || [ -z "${AGENT_TOKEN:-}" ]; then
    echo "ERROR: AGENT_ID and AGENT_TOKEN must be set." >&2
    echo "       Provision them at: https://sentinelai.cloud/api/v1/agents/provision" >&2
    exit 1
fi

# ── System user ───────────────────────────────────────────────────────────────
if ! id "$SERVICE_USER" &>/dev/null; then
    useradd --system --no-create-home --shell /bin/false "$SERVICE_USER"
    echo "Created system user: $SERVICE_USER"
fi

# ── Download agent files from GitHub ─────────────────────────────────────────
# NOTE: We always clone from GitHub so this script works when piped via
# "curl | bash". In that mode bash reads from stdin, BASH_SOURCE[0] is unset,
# and we cannot derive __file__. A git clone is the only reliable approach.
echo "==> Downloading agent files from ${REPO_URL} ..."
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

git clone --depth 1 --quiet "$REPO_URL" "$TMP_DIR/repo"

mkdir -p "$INSTALL_DIR"
if [ -d "$TMP_DIR/repo/$AGENT_SUBDIR" ]; then
    cp -r "$TMP_DIR/repo/$AGENT_SUBDIR/." "$INSTALL_DIR/"
else
    # Fallback: the whole repo IS the agent (standalone sentinel-agent repo)
    cp -r "$TMP_DIR/repo/." "$INSTALL_DIR/"
fi

chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
echo "    Installed to $INSTALL_DIR"

# ── Python virtual environment ────────────────────────────────────────────────
echo "==> Setting up Python virtual environment ..."
python3 -m venv "$INSTALL_DIR/venv"
"$INSTALL_DIR/venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"
echo "    Dependencies installed"

# ── Environment / config file ─────────────────────────────────────────────────
mkdir -p "$ENV_DIR"
chmod 750 "$ENV_DIR"
chown root:"$SERVICE_USER" "$ENV_DIR"

cat > "$ENV_DIR/env" <<ENVEOF
# Sentinel Agent Configuration — generated by install.sh
# Edit this file, then: systemctl restart sentinel-agent

AGENT_ID=${AGENT_ID}
AGENT_TOKEN=${AGENT_TOKEN}
BRAIN_URL=${BRAIN_URL:-wss://sentinelai.cloud/ws/agent}
APP_NAME=${APP_NAME:-app}
APP_DIR=${APP_DIR:-/opt/app}
APP_PROCESS_NAME=${APP_PROCESS_NAME:-python}
APP_HEALTH_URL=${APP_HEALTH_URL:-}
APP_LOG_PATH=${APP_LOG_PATH:-}
APP_RESTART_CMD=${APP_RESTART_CMD:-}
APP_TEST_CMD=${APP_TEST_CMD:-}
SENTINEL_ENV=${SENTINEL_ENV:-staging}
HEARTBEAT_INTERVAL=${HEARTBEAT_INTERVAL:-30}
ENVEOF

chmod 640 "$ENV_DIR/env"
chown root:"$SERVICE_USER" "$ENV_DIR/env"
echo "    Config written to $ENV_DIR/env"

# ── Systemd service ───────────────────────────────────────────────────────────
cp "$INSTALL_DIR/sentinel-agent.service" /etc/systemd/system/sentinel-agent.service
systemctl daemon-reload
systemctl enable sentinel-agent
systemctl restart sentinel-agent

echo ""
echo "==> Sentinel Agent installed and started"
echo "    Status : systemctl status sentinel-agent"
echo "    Logs   : journalctl -u sentinel-agent -f"
echo "    Config : $ENV_DIR/env"
echo ""
echo "    Agent ID  : ${AGENT_ID}"
echo "    Brain URL : ${BRAIN_URL:-wss://sentinelai.cloud/ws/agent}"
echo "    Env       : ${SENTINEL_ENV:-staging}"
