version = 5.3.1
archive_dir = /etc/letsencrypt/archive/sentinelai.cloud
cert = /etc/letsencrypt/live/sentinelai.cloud/cert.pem
privkey = /etc/letsencrypt/live/sentinelai.cloud/privkey.pem
chain = /etc/letsencrypt/live/sentinelai.cloud/chain.pem
fullchain = /etc/letsencrypt/live/sentinelai.cloud/fullchain.pem
[renewalparams]
account = 474c8ffedb5c2c03bec28abe9f9ac785
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-03-04T05:19:50
